project:
  type: website
  output-dir: docs
  
website:
  title: "Carolina"
  favicon: images/favicon.png
  navbar:
    background: "#eeeeee"
    foreground: "#000000"
    logo: images/favicon.png
    # logo-href: 
    search: true
    pinned: true
    collapse: true
    right:
      - href: index.qmd
        text: About me
      - resume.qmd
      - blog.qmd
      - projects.qmd
  page-footer:
    background: "#000000"
    left:
    - "Copyright 2023, Carolina Cornejo Castellano"
    right:
    - icon: linkedin
      href: https://linkedin.com/in/castellco
    - icon: github
      href: https://github.com/castellco
format:
  html:
    theme: [lux, styles.scss]
    css: styles.css
    toc: true
    page-layout: full
    header-includes: |
       <link href="https://fonts.googleapis.com/css2?family=Stylish&display=swap" rel="stylesheet"> 
    mainfont: 'Stylish'
    
