project:
  type: website
  output-dir: docs
  
website:
  title: "Carolina C.C."
  site-url: https://castellco.github.io
  description: "Máster en Ciencias Sociales Computacionales"
  favicon: images/favicon.png
  twitter-card: true
  navbar:
    logo: images/favicon.png
    background: $black
    search: true
    pinned: false
    collapse: true
    right:
      - href: index.qmd
        text: Sobre mí
      # - blog.qmd
      - projects.qmd
  page-footer:
    background: $black
    left:
    - "Copyright 2025, Carolina Cornejo Castellano"
    right:
    - icon: linkedin
      href: https://linkedin.com/in/castellco
    - icon: github
      href: https://github.com/castellco
format:
  html:
    theme: [lux, styles.scss]
    css: styles.css
    toc: true
    page-layout: full